### ISSUE TITLE
Static server

### ISSUE THREAD

**Issue by TheBox193** [adamsea/recipes-client#3]
I've noticed that the project is using `static -p 9000 .` for the `npm run start` and this really ought to be resolved either in the script or via using something cleaner that requires no user setup. I did some googling and was unable to locate where to install `static` for either my mac or windows box. Perhaps `brew install`, but that won't work for windows users..

As far as I can tell from the script there is no mention how to setup the dependences of the `static` command unless I missed it. I know on mac the de-facto go to is `python -m SimpleHTTPServer 9000`, however since python isn't installed on windows by default, that might be a barrier to using it. I'm unsure if that works in the windows environment.

For testing purposes as I go though things, I'll be using `python -m SimpleHTTPServer 9000` myself until we have a solid answer. :+1: 

https://github.com/adamsea/recipes-client/blob/master/package.json#L9

**Comment by adamsea** [comment]
Hello - yes this was fixed for the final codebase.  Node-static is installed as a local dependency and run using `npm run start`.  Thanks!

**Comment by TheBox193** [comment]
Good to hear 👍
